name: CD - Terraform with approval

on:
  push:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init/plan
        run: |
          terraform -chdir=terraform init -input=false
          terraform -chdir=terraform plan -out=plan.tfplan
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/plan.tfplan

  approve:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo "Waiting for manual approval in Environments"

  apply:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        run: terraform -chdir=terraform apply -auto-approve plan.tfplan